### ISSUE TITLE
Name games re canonical/maas namespace have broken the provider's ability to build

### ISSUE THREAD

**Issue by sempervictus** [canonical/terraform-provider-maas#205]
The current `master` branch fails to build (testing #200 with dependabot changes committed). Why is the namespace being altered? Is MaaS breaking off into a separate company or still tied to Canonical's situation? Our PKGBUILD uses
```sh
build() {
    msg2 "Build program"
    cd "$srcdir/src/$_gourl/$_pkgrname"
    GOPATH="$srcdir" PATH="$srcdir/bin:$PATH" go mod tidy
    GOPATH="$srcdir" PATH="$srcdir/bin:$PATH" make build
}
```
which has worked just fine up until the last set of dependabot changes (we can compare #200 as is against #200 rebased on master for clarity) resulted in this fine mess:
```go
go: terraform-provider-maas/maas imports
	github.com/maas/gomaasclient/client: github.com/maas/gomaasclient@v0.6.0: parsing go.mod:
	module declares its path as: github.com/canonical/gomaasclient
	        but was required as: github.com/maas/gomaasclient

```

**Comment by troyanov** [comment]
Hi @sempervictus

> The current master branch fails to build

There are no build issues with the `master` branch.
```
❯ git clone https://github.com/maas/terraform-provider-maas
❯ cd terraform-provider-maas
❯ git rev-parse --short @
f5a5c2a
❯ go mod tidy
❯ make build
mkdir -p /private/tmp/terraform-provider-maas/bin
go build -o /private/tmp/terraform-provider-maas/bin/terraform-provider-maas
```


> resulted in this fine mess

Maybe you are using your own fork? There is no `maas/gomaasclient@v0.6.0`
https://github.com/maas/terraform-provider-maas/blob/f5a5c2a50d80a980bc7889e785773f8ee283d2b5/go.mod#L7

The last version of `maas/gomaasclient` is `v0.5.0` while `canonical/gomaasclient` was published with `v0.6.0`
The error message you are facing is most likely because you did `go get  -u` (which already means you are not building the latest `master`)
```
go: downloading github.com/maas/gomaasclient v0.6.0
go: github.com/maas/gomaasclient@upgrade (v0.6.0) requires github.com/maas/gomaasclient@v0.6.0: parsing go.mod:
	module declares its path as: github.com/canonical/gomaasclient
	        but was required as: github.com/maas/gomaasclient
```

> Why is the namespace being altered

Namespace was not changed. We changed `gomaasclient` Go module name.
The change was made because we were transferring `maas/gomaasclient` ownership under [Canonical](https://github.com/canonical) organisation. 
 
According to Semantic Versioning Specification (SemVer) this module rename was absolutely legit as we were still under 0.x.x
>Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

But as I said, this change doesn't affect `master` and you can still build 6152862 or a46577a or any other commit.

> we can compare https://github.com/maas/terraform-provider-maas/pull/200 as is against https://github.com/maas/terraform-provider-maas/pull/200 rebased on master for clarity

You linked two identical PRs. What changes should I observe there?

> Name games

We had an announcement regarding this rename and gave certain amount of time for people to prepare for possible CI issues:
https://discourse.maas.io/t/gomaasclient-ownership-changing/8401
https://github.com/canonical/gomaasclient/pull/66/files

**Comment by sempervictus** [comment]
Apologies, double-link is just my noting which PR i was working on at the time.
How are you building? Our CI does a clean choot build every time:
syncs `git+https://github.com/maas/maas`
then runs these two functions in order failing during `build()` (`$_pkgrname` == `maas`)
```
prepare() {
    mkdir -p "$srcdir/src/$_gourl"
    rm -rf "${srcdir}/src/$_gourl/$_pkgrname"
    mv -f "$srcdir/$_pkgrname" "$srcdir/src/$_gourl/$_pkgrname"
}
build() {
    msg2 "Build program"
    cd "$srcdir/src/$_gourl/$_pkgrname"
    GOPATH="$srcdir" PATH="$srcdir/bin:$PATH" go mod tidy
    GOPATH="$srcdir" PATH="$srcdir/bin:$PATH" make build
}
```
this is Arch Linux so Go is at `1.22.4-1` in case that matters (i can caveman around the language somewhat but far less familiar w/ it and the toolchains than Rust for example).

Wondering if i'm seeing some sort of caching effect or mismatch but i've had this happen in the CI and locally (same idea - clean chroot per build) :-\.

**Comment by troyanov** [comment]
> How are you building?

These are the steps I did locally (but I was checking `master`, not https://github.com/canonical/terraform-provider-maas/pull/200):
```
❯ git clone https://github.com/maas/terraform-provider-maas
❯ cd terraform-provider-maas
❯ git rev-parse --short @
f5a5c2a
❯ go mod tidy
❯ make build
mkdir -p /private/tmp/terraform-provider-maas/bin
go build -o /private/tmp/terraform-provider-maas/bin/terraform-provider-maas
```


One thing I've noticed in your https://github.com/canonical/terraform-provider-maas/pull/200 is that you refer to an old module name
https://github.com/canonical/terraform-provider-maas/blob/5520033e5f11a40e88dacaf49cc0fdb92a91c990/maas/data_source_maas_block_revice.go#L9

Can you change this to `github.com/canonical/gomaasclient/client`?

**Comment by sempervictus** [comment]
Did I copy-paste the resource to a data source just as you changed dependency string? :)

Will make that change and push

**Comment by sempervictus** [comment]
yup, TOCTOU problem with my taking the `resource` code and using it for `data` source when the dependencies were changing in `master`.
